name: test_xylophone_flutter
description: xylophone flutter
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  audioplayers: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/avatar1.jpg
    - assets/avatar2.jpg
    - assets/avatar3.jpg
    - assets/avatar4.jpg
    - assets/audio1_en.wav
    - assets/audio1_jp.wav
    - assets/audio2_en.wav
    - assets/audio2_jp.wav
    - assets/audio3_en.wav
    - assets/audio3_jp.wav
    - assets/audio4_en.wav
    - assets/audio4_jp.wav
